export const FETCH_LAST_SALARY_SUCCESS = 'FETCH_LAST_SALARY_SUCCESS';
export const FETCH_SUM_OF_YEAR_SALARY_SUCCESS = 'FETCH_SUM_OF_YEAR_SALARY_SUCCESS';
export const FETCH_SEND_MONEY_SUCCESS = 'FETCH_SEND_MONEY_SUCCESS';
export const FETCH_CURRENT_MONEY_SUCCESS = 'FETCH_CURRENT_MONEY_SUCCESS';